name = "Open Skies"
author = "AlphaMode"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1104069b7e78f70ca5b8206195c5f4198ff9daa5fca85b542acfeef69f8b49c"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"
