name = "Open Skies"
author = "AlphaMode"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f6822e29bb82a7bc3f79185226992d72a191983706b17dc3c9ff4efa09a7af"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"
