name = "Conjuring"
filename = "conjuring-1.0.11.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GriMtaoD/versions/1.0.11/conjuring-1.0.11.jar"
hash-format = "sha512"
hash = "073fe7969dcf195562b26019d0690cd6a0a3504b5a619e1ea3c1427ec05bd7fbd52f29be89f87c16d8a5c52dc63009f7b3c3a7c80fda855b888b3c89db955a68"

[update]
[update.modrinth]
mod-id = "GriMtaoD"
version = "R9rgpXkc"
